// <auto-generated />
using File_Upload.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace File_Upload.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241210055924_GiftTable-Withimage")]
    partial class GiftTableWithimage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("File_Upload.Models.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiftImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiftImage = "https://media.istockphoto.com/id/1443034333/photo/christmas-or-birthday-gift-box-on-white-wooden-table-against-blue-turquoise-bokeh-lights.jpg?s=612x612&w=0&k=20&c=9EzZqIg271JMqgd5m6JutoPxrsKtQAXzM-r_QyHTkws="
                        },
                        new
                        {
                            Id = 2,
                            GiftImage = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZoVPSd6j-4ifkP5-Ec63-2GIsB29FMM5g9w&s"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
